
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import tkinter
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import requests
import pyperclip
import paramiko
import pandas as pd
import datetime

sheet_id = "1XQsOzCat4K0AH0VAfVfl8JK91zz5szCSc8c9UpHVkjE"
df = pd.read_csv(f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv")


startYr = df.iloc[7,7]
startMth =df.iloc[7,8]
startDay =df.iloc[7,9]
startHr =df.iloc[7,10]
startMin=df.iloc[7,11]

#End date 1
endYr = df.iloc[8,7]
endMth =df.iloc[8,8]
endDay =df.iloc[8,9]
endHr =df.iloc[8,10]
endMin =df.iloc[8,11]

ExpireReason = df.iloc[9,7] #Expire Reason



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\\RMA Tools\\LAP_PR\\assets\\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def can_run_script():           #Add Time Trial
    now = datetime.datetime.now()
    #start_datetime = datetime.datetime(2023, 8, 18, 21, 0)  # 2 PM on 18 Aug 2023
    #end_datetime = datetime.datetime(2023, 8, 18, 21, 2)    # 3 PM on 19 Aug 2023

    start_datetime = datetime.datetime( int(startYr),int(startMth),int(startDay),int(startHr),int(startMin))
    end_datetime = datetime.datetime( int(endYr),int(endMth),int(endDay),int(endHr),int(endMin))
    if start_datetime <= now <= end_datetime:
        return True
    return False

def format_mac_address(mac_str):
    if len(mac_str) == 17 and all(c in "0123456789abcdefABCDEF-" for c in mac_str):
        number = mac_str.replace('-', '')
    elif len(mac_str) == 12 and all(c in "0123456789abcdefABCDEF" for c in mac_str):
        number = mac_str
    elif len(mac_str) == 17 and all(c in "0123456789abcdefABCDEF:" for c in mac_str):
        number = mac_str.replace(":","")
    else:
        return "Invalid input. Please provide input in format aa-bb-cc-dd-ee-ff or aabbccddeeff."

    mac = ":".join([number[i:i+2] for i in range(0, 12, 2)])
    return mac

def KeyGen():
    mac = entry_2.get()
    macformatted = format_mac_address(mac)
    #print(macformatted)
    url = f"http://pwdhash.frontiir.net:5101/v1/openwrt?mac={macformatted}"
    response = requests.get(url)

    if response.status_code == 200:
        uniquekeygen = response.text.strip()
        entry_3.delete(0, tkinter.END)
        entry_3.insert(0,string=str(uniquekeygen))

    else:
        entry_3.delete(0,tkinter.END)
        entry_3.insert(0,string=str("Invalid MAC"))

def Copy():
    pyperclip.copy(entry_3.get())
    entry_4.delete(0, tkinter.END)
    entry_4.insert(0,string=str("Copied"))

def Paste():
    entry_2.delete(0,tkinter.END)
    entry_2.insert(0,string=str(pyperclip.paste()))
    entry_1.delete(0,tkinter.END)
    entry_3.delete(0, tkinter.END)
    entry_4.delete(0, tkinter.END)

def establish_ssh_connection(ip_address, username, password):   #SSH Connection
    ssh_client = paramiko.SSHClient()
    ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh_client.connect(ip_address, username=username, password=password)
    return ssh_client

def execute_ssh_command(ssh_client, command):   #SSH Command
    stdin, stdout, stderr = ssh_client.exec_command(command)
    output = stdout.read().decode()
    return output

def ProbRemov():    #with Unique Key
    LAPip="192.168.20.1"
    UniqueKey=entry_3.get()

    
    ssh_client = establish_ssh_connection(LAPip, "root", UniqueKey)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Provision Removed !"))
    
def ProbRemov7890():    #with 7890
    LAPip="192.168.20.1"
    pass7890="7890"

    
    ssh_client = establish_ssh_connection(LAPip, "root", pass7890)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Provision Removed !"))

def ProbRemovwithb():   #with Binary
    LAPip="192.168.20.1"
    UniqueKey=entry_3.get()
    passwdwithb=f"b\'{UniqueKey}\'"

    
    ssh_client = establish_ssh_connection(LAPip, "root", passwdwithb)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Provision Removed !"))

def ProbRemovFrontiir():    #with Frontiir
    LAPip="192.168.20.1"
    passwdwithF="Fr0nt!!r"
    
    ssh_client = establish_ssh_connection(LAPip, "root", passwdwithF)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Provision Removed !"))

def OpenWrtwithUniKey():  
    LAPip="192.168.1.2"
    UniqueKey=entry_3.get()

    
    ssh_client = establish_ssh_connection(LAPip, "root", UniqueKey)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Issue Fixed !"))

def OpenWrtwithBinary():
    LAPip="192.168.1.2"
    UniqueKey=entry_3.get()
    passwdwithb=f"b\'{UniqueKey}\'"

    
    ssh_client = establish_ssh_connection(LAPip, "root", passwdwithb)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Issue Fixed !"))

def SSHIssuefix():
    LAPip="192.168.1.2"
    passwdwithF="Fr0nt!!r"
    
    ssh_client = establish_ssh_connection(LAPip, "root", passwdwithF)
    ProbRemove = "rm -fr /overlay/upper/*"
    Rebooot = "reboot"
    execute_ssh_command(ssh_client, ProbRemove)
    execute_ssh_command(ssh_client, Rebooot)
    ssh_client.close()
    entry_1.insert(0,string=str("Issue Fixed!"))

window = Tk()

window.geometry("550x450")
window.configure(bg = "#FF4500")
window.iconbitmap('C:\\RMA Tools\\LAP_PR\\rmalogo.ico')
window.title("LAP Provision Remover v2.0")


canvas = Canvas(
    window,
    bg = "#FF4500",
    height = 450,
    width = 550,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    274.99999999999994,
    250.99999999999997,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    font=("impact",20),
    bg="#FF4500",
    fg="Yellow",
    highlightthickness=0
)
entry_1.place(
    x=174.99999999999994,
    y=230.99999999999997,
    width=200.0,
    height=38.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    394.99999999999994,
    102.99999999999997,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    font=("impact",16),
    bg="#FF4500",
    fg="Yellow",
    highlightthickness=0
)
entry_2.place(
    x=274.99999999999994,
    y=87.99999999999997,
    width=240.0,
    height=28.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    394.99999999999994,
    152.99999999999997,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    font=("impact",16),
    bg="#FF4500",
    fg="Yellow",
    highlightthickness=0
)
entry_3.place(
    x=274.99999999999994,
    y=137.99999999999997,
    width=240.0,
    height=28.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    394.99999999999994,
    204.99999999999997,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    font=("impact",16),
    bg="#FF4500",
    fg="Yellow",
    highlightthickness=0
)
entry_4.place(
    x=324.99999999999994,
    y=189.99999999999997,
    width=140.0,
    height=28.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=KeyGen,
    relief="flat"
)
button_1.place(
    x=20.999999999999943,
    y=137.99999999999997,
    width=120.0,
    height=30.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=Copy,
    relief="flat"
)
button_2.place(
    x=20.999999999999943,
    y=189.99999999999997,
    width=120.0,
    height=30.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=Paste,
    relief="flat"
)
button_3.place(
    x=20.999999999999943,
    y=87.99999999999997,
    width=120.0,
    height=30.0
)

canvas.create_rectangle(
    5.684341886080802e-14,
    2.842170943040401e-14,
    550.0,
    60.00000000000003,
    fill="#DAA520",
    outline="")

canvas.create_text(
    70.99999999999994,
    9.999999999999972,
    anchor="nw",
    text="LAP PROVISION REMOVER",
    fill="#FFFFFF",
    font=("Inter Medium", 32 * -1)
)

canvas.create_rectangle(
    17.999999999999943,
    277.0,
    267.99999999999994,
    437.0,
    fill="#D9D9D9",
    outline="")

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=ProbRemovwithb,
    relief="flat"
)
button_4.place(
    x=155.99999999999994,
    y=301.0,
    width=64.0,
    height=64.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=ProbRemov7890,
    relief="flat"
)
button_5.place(
    x=49.99999999999994,
    y=371.0,
    width=64.0,
    height=64.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=ProbRemovFrontiir,
    relief="flat"
)
button_6.place(
    x=155.99999999999994,
    y=371.0,
    width=64.0,
    height=64.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=ProbRemov,
    relief="flat"
)
button_7.place(
    x=49.99999999999994,
    y=300.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    98.99999999999994,
    277.0,
    anchor="nw",
    text="Provision",
    fill="#000000",
    font=("Inter Medium", 20 * -1)
)

canvas.create_rectangle(
    281.99999999999994,
    277.0,
    532.0,
    437.0,
    fill="#D9D9D9",
    outline="")

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=OpenWrtwithBinary,
    relief="flat"
)
button_8.place(
    x=327.99999999999994,
    y=370.0,
    width=64.0,
    height=64.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=SSHIssuefix,
    relief="flat"
)
button_9.place(
    x=433.99999999999994,
    y=371.0,
    width=64.0,
    height=64.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=OpenWrtwithUniKey,
    relief="flat"
)
button_10.place(
    x=375.99999999999994,
    y=305.0,
    width=64.0,
    height=64.0
)

canvas.create_text(
    358.99999999999994,
    277.0,
    anchor="nw",
    text="OpenWRT",
    fill="#000000",
    font=("Inter Medium", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
